### ISSUE TITLE
CascadeChoiceParameter is unsupported

### ISSUE THREAD

**Issue by psuvjd** [MCMicS/jenkins-control-plugin#251]
![image](https://user-images.githubusercontent.com/16028643/95979536-5b7ba580-0e4e-11eb-8ee0-1a0efbe5b6f5.png)
Could you add support for this? possibly similar to #249 

The Jenkins plugin is https://plugins.jenkins.io/uno-choice/.

The parameter type is "Active Choices Reactive Parameter".
![image](https://user-images.githubusercontent.com/16028643/95979739-ae555d00-0e4e-11eb-90d1-45d8bd352077.png)

**Comment by MCMicS** [comment]
I will look at this plugin api result these days. Maybe it will released next week if all data are available

**Comment by MCMicS** [comment]
We have an similar issue #171 
Do you have a sample job pipeline for this or some snippets to configure a job for your needed settings

**Comment by MCMicS** [comment]
I cannot get any values from API
```yaml
{
  "_class": "hudson.model.FreeStyleProject",
  "property": [
    {
      "_class": "hudson.model.ParametersDefinitionProperty",
      "parameterDefinitions": [
        {
          "_class": "org.biouno.unochoice.ChoiceParameter",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "Option 1"
          },
          "description": "Active Choices Single",
          "name": "Active Choices Single",
          "type": "ChoiceParameter"
        },
        {
          "_class": "org.biouno.unochoice.ChoiceParameter",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "Option 1"
          },
          "description": "Active Choices Multi",
          "name": "Active Choices Multi",
          "type": "ChoiceParameter"
        },
        {
          "_class": "org.biouno.unochoice.ChoiceParameter",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "Option 1"
          },
          "description": "",
          "name": "Active Choices Radio",
          "type": "ChoiceParameter"
        },
        {
          "_class": "org.biouno.unochoice.ChoiceParameter",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "Option 1"
          },
          "description": "",
          "name": "ActiveChoicesCheck",
          "type": "ChoiceParameter"
        },
        {
          "_class": "org.biouno.unochoice.CascadeChoiceParameter",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": "Option 1"
          },
          "description": "return ['Option 1', 'Option 2', 'Option 3']",
          "name": "Reactive Single",
          "type": "CascadeChoiceParameter"
        },
        {
          "_class": "org.biouno.unochoice.DynamicReferenceParameter",
          "defaultParameterValue": {
            "_class": "hudson.model.StringParameterValue",
            "value": ""
          },
          "description": "",
          "name": "Active Choices Reference Parameter",
          "type": "DynamicReferenceParameter"
        }
      ]
    }
  ]
}

```
